CREATE DATABASE USUARIO;

USE USUARIO;

CREATE TABLE REGISTRO(
ID int primary key auto_increment,,
NOMBRE	VARCHAR(45) NOT NULL,
USUARIO	VARCHAR(20) NOT NULL,
CORREO	VARCHAR(25) NOT NULL,
CONTRASENA VARCHAR(30) NOT NULL,
FECHA_NAC DATE NOT NULL,
CIUDAD VARCHAR(40) NOT NULL);

